# Generated by Django 6.0.3 on 2026-04-20 02:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField()),
                ('room_number', models.TextField()),
                ('building_name', models.TextField()),
                ('max_enrollment', models.IntegerField()),
            ],
            options={
                'db_table': 'classroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstraintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.TextField()),
                ('description', models.TextField()),
                ('constraint_rule', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'constraint_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_number', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.TextField()),
                ('min_credits', models.IntegerField(blank=True, null=True)),
                ('max_credits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.IntegerField()),
                ('semester', models.TextField()),
                ('section_number', models.IntegerField(default=1)),
                ('maximum_enrollment', models.IntegerField(blank=True, null=True)),
                ('actual_enrollment', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'course_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.TextField(unique=True)),
                ('days', models.TextField()),
                ('num_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting_pattern',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
            options={
                'db_table': 'professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_days', models.TextField(blank=True, null=True)),
                ('preferred_time_slots', models.TextField(blank=True, null=True)),
                ('avoid_time_slots', models.TextField(blank=True, null=True)),
                ('preferred_courses', models.TextField(blank=True, null=True)),
                ('avoid_courses', models.TextField(blank=True, null=True)),
                ('min_gap_between_classes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'professor_preference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleMeetingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_duration_minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule_meeting_block',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
                ('duration_minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'time_slot',
                'managed': False,
            },
        ),
    ]
