# Generated by Django 6.0.3 on 2026-04-20 03:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_number', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.TextField()),
                ('min_credits', models.IntegerField(blank=True, null=True)),
                ('max_credits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeetingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.TextField(unique=True)),
                ('days', models.TextField()),
                ('num_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting_pattern',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
            options={
                'db_table': 'professor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField()),
                ('room_number', models.TextField()),
                ('building_name', models.TextField()),
                ('max_enrollment', models.IntegerField()),
            ],
            options={
                'db_table': 'classroom',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('building_id', 'room_number'), name='classroom_building_room_unique')],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.IntegerField()),
                ('semester', models.TextField()),
                ('section_number', models.IntegerField(default=1)),
                ('maximum_enrollment', models.IntegerField(blank=True, null=True)),
                ('actual_enrollment', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(db_column='course_number', on_delete=django.db.models.deletion.CASCADE, to='optimizer.course')),
            ],
            options={
                'db_table': 'course_section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConstraintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.TextField()),
                ('description', models.TextField()),
                ('constraint_rule', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(default=1)),
                ('involves_course', models.ForeignKey(blank=True, db_column='involves_course_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.course')),
                ('involves_professor', models.ForeignKey(blank=True, db_column='involves_professor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.professor')),
            ],
            options={
                'db_table': 'constraint_record',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfessorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_days', models.TextField(blank=True, null=True)),
                ('preferred_time_slots', models.TextField(blank=True, null=True)),
                ('avoid_time_slots', models.TextField(blank=True, null=True)),
                ('preferred_courses', models.TextField(blank=True, null=True)),
                ('avoid_courses', models.TextField(blank=True, null=True)),
                ('min_gap_between_classes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('professor', models.OneToOneField(db_column='professor_id', on_delete=django.db.models.deletion.CASCADE, to='optimizer.professor')),
            ],
            options={
                'db_table': 'professor_preference',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SavedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semester', models.TextField()),
                ('solution_data', models.JSONField()),
                ('stats_data', models.JSONField()),
                ('weights_used', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(blank=True, db_column='classroom_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.classroom')),
                ('course_section', models.OneToOneField(db_column='course_section_id', on_delete=django.db.models.deletion.CASCADE, to='optimizer.coursesection')),
                ('professor', models.ForeignKey(blank=True, db_column='professor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.professor')),
            ],
            options={
                'db_table': 'schedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
                ('duration_minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'time_slot',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('start_time', 'end_time'), name='time_slot_start_end_unique')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleMeetingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('meeting_pattern', models.ForeignKey(db_column='meeting_pattern_id', on_delete=django.db.models.deletion.CASCADE, to='optimizer.meetingpattern')),
                ('schedule', models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.CASCADE, to='optimizer.schedule')),
                ('time_slot', models.ForeignKey(db_column='time_slot_id', on_delete=django.db.models.deletion.CASCADE, to='optimizer.timeslot')),
            ],
            options={
                'db_table': 'schedule_meeting_block',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('semester', 'crn'), name='course_section_sem_crn_unique'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('semester', 'course', 'section_number'), name='course_section_sem_course_section_unique'),
        ),
        migrations.AddConstraint(
            model_name='schedulemeetingblock',
            constraint=models.UniqueConstraint(fields=('schedule', 'time_slot', 'meeting_pattern'), name='schedule_meeting_block_unique'),
        ),
    ]
