# Generated by Django 6.0.3 on 2026-04-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(blank=True, db_column='course_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.course'),
        ),
        migrations.AlterField(
            model_name='professorpreference',
            name='professor',
            field=models.OneToOneField(blank=True, db_column='professor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.professor'),
        ),
    ]
