# Generated by Django 6.0.3 on 2026-04-20 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='constraintrecord',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='meetingpattern',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='professorpreference',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='schedulemeetingblock',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='SavedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semester', models.TextField()),
                ('solution_data', models.JSONField()),
                ('stats_data', models.JSONField()),
                ('weights_used', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
