# Generated by Django 6.0.3 on 2026-04-20 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_alter_coursesection_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorpreference',
            name='avoid_courses',
        ),
        migrations.RemoveField(
            model_name='professorpreference',
            name='avoid_time_slots',
        ),
        migrations.RemoveField(
            model_name='professorpreference',
            name='min_gap_between_classes',
        ),
        migrations.RemoveField(
            model_name='professorpreference',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='professorpreference',
            name='preferred_courses',
        ),
        migrations.RemoveField(
            model_name='professorpreference',
            name='preferred_days',
        ),
        migrations.RemoveField(
            model_name='professorpreference',
            name='preferred_time_slots',
        ),
        migrations.AddField(
            model_name='professorpreference',
            name='avoid_back_to_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professorpreference',
            name='day_pattern',
            field=models.CharField(choices=[('MWF', 'Mon/Wed/Fri'), ('TR', 'Tue/Thu'), ('MW', 'Mon/Wed'), ('any', 'No Preference')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='professorpreference',
            name='level_preference',
            field=models.CharField(choices=[('lower', 'Lower Division (1000-2000)'), ('upper', 'Upper Division (3000-4000)'), ('grad', 'Graduate (5000+)'), ('any', 'No Preference')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='professorpreference',
            name='max_sections',
            field=models.CharField(choices=[('1', '1 Section'), ('2', '2 Sections'), ('3', '3 Sections'), ('4', '4+ Sections'), ('any', 'No Preference')], default='any', max_length=5),
        ),
        migrations.AddField(
            model_name='professorpreference',
            name='tenured',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='professorpreference',
            name='time_of_day',
            field=models.CharField(choices=[('morning', 'Morning (8-11am)'), ('midday', 'Midday (11am-2pm)'), ('afternoon', 'Afternoon (2-6pm)'), ('no_early', 'No Early Morning'), ('no_late', 'No Late Afternoon'), ('any', 'No Preference')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='professorpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='professorpreference',
            name='professor',
            field=models.OneToOneField(blank=True, db_column='professor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='optimizer.professor'),
        ),
    ]
