# Generated by Django 6.0.3 on 2026-04-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_remove_professorpreference_avoid_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
