# Generated by Django 6.0.3 on 2026-04-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0004_professor_is_active'),
        ('optimizer', '0005_courseconfig'),
    ]

    operations = [
    ]
