# Generated by Django 6.0.3 on 2026-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0007_savedschedule_editor_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedschedule',
            name='editor_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='savedschedule',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
